apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-team6
  namespace: api-dev
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "899f6f6c-1a30-4f12-970b-1b5b62172be7"
    keyvaultName: "kv-aks-team6"
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: sql-user
          objectType: secret
          objectAlias: SQL_USER
          objectVersion: ""
        - |
          objectName: sql-pwd
          objectType: secret
          objectAlias: SQL_PASSWORD
          objectVersion: ""
        - |
          objectName: sql-fqdn
          objectType: secret
          objectAlias: SQL_SERVER
          objectVersion: ""

    resourceGroup: "teamResources"
    subscriptionId: "40de141e-fd99-463e-87a3-be24e46f5337"
    tenantId: "0a91962f-e7af-4631-a5d5-be8a320e4164"
