kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-dev-full-access
  namespace: web-dev
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-dev-access
  namespace: web-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-dev-full-access
subjects:
- kind: Group
  namespace: web-dev
  name: groupObjectId
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: api-dev-full-access
    namespace: api-dev
rules:
- apiGroups: ["", "extensions", "apps"]
    resources: ["*"]
    verbs: ["*"]
- apiGroups: ["batch"]
    resources:
    - jobs
    - cronjobs
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: api-dev-access
    namespace: web-dev
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: web-dev-full-access
subjects:
- kind: Group
    namespace: web-dev
    name: groupObjectId  
