apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: user-java
        image: registryjpn0775.azurecr.io/user-java:v1
        env:
        - name: SQL_USER
          value: "sqladminjPn0775"
        - name: SQL_PASSWORD
          value: "nH9ju5Cb2"
        - name: SQL_SERVER
          value: "sqlserverjpn0775.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: user-java
spec:
  ports:
  - port: 80
  selector:
    app: user-java